import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';


import { Login } from 'components/Login';
import useAuthSession from 'hooks/useAuthSession';

const Home: NextPage = () => {
  const {authSession, authIsLoading} = useAuthSession();

  return (
    <div className=' w-screen h-screen flex flex-col items-center justify-center' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {authSession? <div>
        <h2>{authSession.user.email}</h2>
      </div> :<Login />}
    </div>
  );
};

export default Home;
