import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Login } from '../components/login';

const Home: NextPage = () => {
  return (
    <div className=' w-screen h-screen flex flex-col items-center justify-center' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
};

export default Home;
